# Look for the header file.
FIND_PATH(FASTCGIQT_INCLUDE_DIR NAMES FastCgiQt/Request.h)

# Look for the library.
FIND_LIBRARY(FASTCGIQT_LIBRARY NAMES libFastCgiQt FastCgiQt)

# handle the QUIETLY and REQUIRED arguments and set FASTCGIQT_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(FASTCGIQT DEFAULT_MSG FASTCGIQT_LIBRARY FASTCGIQT_INCLUDE_DIR)

# Copy the results to the output variables.
IF(FASTCGIQT_FOUND)
  SET(FASTCGIQT_LIBRARIES ${FASTCGIQT_LIBRARY})
  SET(FASTCGIQT_INCLUDE_DIRS ${FASTCGIQT_INCLUDE_DIR})
ELSE(FASTCGIQT_FOUND)
  SET(FASTCGIQT_LIBRARIES)
  SET(FASTCGIQT_INCLUDE_DIRS)
ENDIF(FASTCGIQT_FOUND)

MARK_AS_ADVANCED(FASTCGIQT_INCLUDE_DIR FASTCGIQT_LIBRARY)
